repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.5.6
  hooks:
    # Run the linter.
    - id: ruff
      types_or: [ python, pyi, jupyter ]
      args: [ --fix ]
    # Run the formatter.
    - id: ruff-format
      types_or: [ python, pyi, jupyter ]
      args: [
        '--config=format.docstring-code-format=true'
      ]
- repo: https://github.com/codespell-project/codespell
  rev: v2.2.6
  hooks:
    - id: codespell
      files: \.(py|smk|md)$
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.10.1
  hooks:
    - id: mypy
      # equivalent to "files" in .mypy.ini
      files: '^(pyani_plus|tests)/'
