repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
    - id: check-added-large-files
    - id: check-case-conflict
    - id: check-executables-have-shebangs
    - id: check-json
    - id: check-merge-conflict
    - id: check-shebang-scripts-are-executable
    - id: check-symlinks
    - id: check-yaml
    - id: debug-statements
    - id: destroyed-symlinks
    - id: end-of-file-fixer
      files: \.(py|sh|smk|md|yml|yaml)$
    - id: mixed-line-ending
    - id: trailing-whitespace
      files: \.(py|sh|smk|md|yml|yaml)$
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.6.1
  hooks:
    # Run the linter.
    - id: ruff
      types_or: [ python, pyi, jupyter ]
      args: [ --fix ]
    # Run the formatter.
    - id: ruff-format
      types_or: [ python, pyi, jupyter ]
      args: [
        '--config=format.docstring-code-format=true'
      ]
- repo: https://github.com/snakemake/snakefmt
  rev: v0.10.2
  hooks:
    - id: snakefmt
- repo: https://github.com/codespell-project/codespell
  rev: v2.3.0
  hooks:
    - id: codespell
      files: \.(py|smk|md)$
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.11.1
  hooks:
    - id: mypy
      # equivalent to "files" in .mypy.ini
      files: '^(pyani_plus|tests)/'
